name = "ProgressTMap"
uuid = "582173b4-e96e-43f2-ad91-374f9af63bd1"
authors = ["Oliver Dudgeon <22367286+OliverDudgeon@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
